@baseUrl = http://localhost:3000/


### Registrar usuario
POST {{baseUrl}}usuario/registro
Content-Type: application/json

{
  "correo": "ccc@ccc.com",
  "contraseña": "1",
  "nombreCompleto": "Juan Pérez"
}

### Login
POST {{baseUrl}}auth/login
Content-Type: application/json

{
  "correo": "juan.perez@gmail.com",
  "contraseña": "MiClave123!"
}